//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradera_Klubb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.GradingTabs = new HashSet<GradingTabs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Settings { get; set; }
    
        public virtual ICollection<GradingTabs> GradingTabs { get; set; }
    }
}
