//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradera_Klubb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combination
    {
        public Combination()
        {
            this.Combination_Technique = new HashSet<Combination_Technique>();
        }
    
        public int id { get; set; }
        public string author { get; set; }
        public string description { get; set; }
        public string ip { get; set; }
        public string date { get; set; }
        public string password { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Combination_Technique> Combination_Technique { get; set; }
    }
}
