//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradera_Klubb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vicdude_graderaEntities : DbContext
    {
        public Vicdude_graderaEntities()
            : base("name=Vicdude_graderaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Combination> Combination { get; set; }
        public virtual DbSet<Combination_Technique> Combination_Technique { get; set; }
        public virtual DbSet<GradingTabs> GradingTabs { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Search> Search { get; set; }
        public virtual DbSet<TECHNICS> TECHNICS { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Wordlist> Wordlist { get; set; }
        public virtual DbSet<Accessright> Accessright { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountAccess> AccountAccess { get; set; }
    }
}
