//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradera_Klubb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECHNICS
    {
        public TECHNICS()
        {
            this.Image = new HashSet<Image>();
            this.Movie = new HashSet<Movie>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string belt { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual ICollection<Image> Image { get; set; }
        public virtual ICollection<Movie> Movie { get; set; }
        public virtual Type Type { get; set; }
    }
}
